name: Build all presets

on:
  # Used when triggering this workflow from another workflow
  workflow_call:
    inputs:
      debug-mode:
        description: "Whether to export the preset in debug mode. Defaults to true"
        required: false
        type: boolean
        default: true

jobs:
  build_all:
    name: Build all presets
    strategy:
      matrix:
        godot-export-preset: ['linux', 'mac', 'windows', 'web']

    uses: ./.github/workflows/build_one.yml
    with:
      godot-export-preset: ${{ matrix.godot-export-preset }}
      debug-mode: ${{ inputs.debug-mode }}
