name: Release builds of all platforms to production channels

on:
  push:
    tags:
      - 'v*'

jobs:
  release_all:
    name: Release all presets to production channels
    strategy:
      matrix:
        godot-export-preset: ['linux', 'mac', 'windows', 'web']

    uses: ./.github/workflows/release_one.yml
    with:
      godot-export-preset: ${{ matrix.godot-export-preset }}
    secrets: inherit
