name: Release to production

on:
  push:
    tags:
      - 'v*'

jobs:
  build_linux:
    name: Build
    uses: ./.github/workflows/build_one.yml
    with:
      godot-export-preset: linux
      debug-mode: false

  release_linux:
    needs: [build_linux]
    name: Release
    uses: ./.github/workflows/release_one.yml
    with:
      release-channel: linux-production
      artifact-name: ${{ needs.build_linux.outputs.artifact-name }}
    secrets: inherit

  build_mac:
    name: Build
    uses: ./.github/workflows/build_one.yml
    with:
      godot-export-preset: mac
      debug-mode: false

  release_mac:
    needs: [build_mac]
    name: Release
    uses: ./.github/workflows/release_one.yml
    with:
      release-channel: mac-production
      artifact-name: ${{ needs.build_mac.outputs.artifact-name }}
    secrets: inherit

  build_web:
    name: Build
    uses: ./.github/workflows/build_one.yml
    with:
      godot-export-preset: web
      debug-mode: false

  release_web:
    needs: [build_web]
    name: Release
    uses: ./.github/workflows/release_one.yml
    with:
      release-channel: web-production
      artifact-name: ${{ needs.build_web.outputs.artifact-name }}
    secrets: inherit

  build_windows:
    name: Build
    uses: ./.github/workflows/build_one.yml
    with:
      godot-export-preset: windows
      debug-mode: false

  release_windows:
    needs: [build_windows]
    name: Release
    uses: ./.github/workflows/release_one.yml
    with:
      release-channel: windows-production
      artifact-name: ${{ needs.build_web.outputs.artifact-name }}
    secrets: inherit

  tag_commit:
    needs: [release_linux, release_mac, release_web, release_windows]

    name: Create tag release-${{ github.run_number }}
    runs-on: ubuntu-latest

    steps:
      - name: Tag commit
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: release-${{ github.run_number }}
          tag_prefix: ""
